# Generated by Django 3.1.7 on 2021-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imagepack_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='diarias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
