# Generated by Django 3.1.7 on 2021-12-14 17:47

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pack_diarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='arrive_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='leave_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 17, 47, 28, 962495, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
