# Generated by Django 3.1.7 on 2022-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='date_arrive',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='date_leave',
        ),
        migrations.AddField(
            model_name='thread',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
