# Generated by Django 3.1.7 on 2022-05-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220518_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thread'),
        ),
    ]
