#! /usr/bin/python
# -*- coding: UTF-8 -*-
"""
Global variables for base module
"""
from django.conf import LazySettings
from django.utils.translation import ugettext_lazy as _

settings = LazySettings()


def get_from_settings_or_default(var_name, default):
    try:
        return settings.__getattr__(var_name)
    except AttributeError:
        return default


# Items by page on paginator views
ITEMS_BY_PAGE = 10

CREATE_SUFFIX = "_create"
LIST_SUFFIX = "_list"
DETAIL_SUFFIX = "_detail"
UPDATE_SUFFIX = "_update"
DELETE_SUFFIX = "_delete"

API_SUFFIX = "_api"
style = "base_django/flexbox"

# Messages
OBJECT_CREATED_SUCCESSFULLY = _("Object created successfully")
OBJECT_UPDATED_SUCCESSFULLY = _("Object updated successfully")
OBJECT_DELETED_SUCCESSFULLY = _("Object deleted successfully")

BASE_MODELS_TRANSLATION_NAME = _("Name")
BASE_MODELS_TRANSLATION_DESCRIPTION = _("Description")
BASE_MODELS_TRANSLATION_SLUG = _("Slug")
BASE_MODELS_TRANSLATION_CREATED = _("Created")
BASE_MODELS_TRANSLATION_MODIFIED = _("Modified")
BASE_MODELS_TRANSLATION_ACTIVE = _("Active")

CONFIGURING_APPLICATION = _("Configuring application {}")
CREATING_PERMISSION_WITH_NAME = _("Creating Permission with name {}")
CREATING_GROUP_WITH_NAME = _("Creating Group with name {}")

TICKET_PREFIX = "TICKET"

TICKET_VERBOSE_NAME = _("Ticket")
TICKET_VERBOSE_NAME_PLURAL = _("Ticket")

TICKET_LIST_URL_NAME = TICKET_PREFIX + LIST_SUFFIX
TICKET_CREATE_URL_NAME = TICKET_PREFIX + CREATE_SUFFIX
TICKET_DETAIL_URL_NAME = TICKET_PREFIX + DETAIL_SUFFIX
TICKET_UPDATE_URL_NAME = TICKET_PREFIX + UPDATE_SUFFIX
TICKET_DELETE_URL_NAME = TICKET_PREFIX + DELETE_SUFFIX
TICKET_LIST_JSON_URL_NAME = TICKET_PREFIX + '_list_json'

PACK_PREFIX = "PACK"

PACK_VERBOSE_NAME = _("Pack")
PACK_VERBOSE_NAME_PLURAL = _("Pack")

PACK_LIST_URL_NAME = PACK_PREFIX + LIST_SUFFIX
PACK_CREATE_URL_NAME = PACK_PREFIX + CREATE_SUFFIX
PACK_DETAIL_URL_NAME = PACK_PREFIX + DETAIL_SUFFIX
PACK_UPDATE_URL_NAME = PACK_PREFIX + UPDATE_SUFFIX
PACK_DELETE_URL_NAME = PACK_PREFIX + DELETE_SUFFIX
PACK_LIST_JSON_URL_NAME = PACK_PREFIX + '_list_json'

IMAGEPACK_PREFIX = "IMAGEPACK"

IMAGEPACK_VERBOSE_NAME = _("ImagePack")
IMAGEPACK_VERBOSE_NAME_PLURAL = _("ImagePack")

IMAGEPACK_LIST_URL_NAME = IMAGEPACK_PREFIX + LIST_SUFFIX
IMAGEPACK_CREATE_URL_NAME = IMAGEPACK_PREFIX + CREATE_SUFFIX
IMAGEPACK_DETAIL_URL_NAME = IMAGEPACK_PREFIX + DETAIL_SUFFIX
IMAGEPACK_UPDATE_URL_NAME = IMAGEPACK_PREFIX + UPDATE_SUFFIX
IMAGEPACK_DELETE_URL_NAME = IMAGEPACK_PREFIX + DELETE_SUFFIX
IMAGEPACK_LIST_JSON_URL_NAME = IMAGEPACK_PREFIX + '_list_json'

THREAD_PREFIX = "THREAD"

THREAD_VERBOSE_NAME = _("Thread")
THREAD_VERBOSE_NAME_PLURAL = _("Thread")

THREAD_LIST_URL_NAME = THREAD_PREFIX + LIST_SUFFIX
THREAD_CREATE_URL_NAME = THREAD_PREFIX + CREATE_SUFFIX
THREAD_DETAIL_URL_NAME = THREAD_PREFIX + DETAIL_SUFFIX
THREAD_UPDATE_URL_NAME = THREAD_PREFIX + UPDATE_SUFFIX
THREAD_DELETE_URL_NAME = THREAD_PREFIX + DELETE_SUFFIX
THREAD_LIST_JSON_URL_NAME = THREAD_PREFIX + '_list_json'

